export const CHANGECITY = 'CHANGECITY' // 更改收货地址
export const CHANGECONSIGNEE = "CHANGECONSIGNEE" // 更改收货人
export const CHANGELOCATIONGCITY = "CHANGELOCATIONGCITY" // 定位城市
export const CHANGEAREAID = "CHANGEAREAID"// 更改地区
export const CHANGEDETAILS = "CHANGEDETAILS" // 更改用户信息
export const CHANGESEARCHTEXT = "CHANGESEARCHTEXT" // 更改搜索值
export const CHANGEBALANCE = "CHANGEBALANCE" // 余额
export const CHANGELATELY = "CHANGELATELY" // 更改最近搜索
export const CHANGEORDERINDEX = "CHANGEORDERINDEX" // 更改订单页tab栏目索引
export const CHANGESKIP = "CHANGESKIP" // 更改后缀数字
